import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';

export const maxDuration = 30;

export async function POST(req: NextRequest) {
  try {
    const { question, documents, apiKey, language } = await req.json();

    if (!question) {
      return NextResponse.json({ error: "question parameter is required" }, { status: 400 });
    }

    if (!apiKey) {
      return NextResponse.json({ error: "apiKey is required for RAG reasoning" }, { status: 400 });
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    let geminiModel = (process.env.GEMINI_MODEL || 'gemini-1.5-flash').trim().replace(/['"]/g, '');
    if (geminiModel.includes('1.0-pro-vision')) geminiModel = 'gemini-1.5-flash';
    const model = genAI.getGenerativeModel({ model: geminiModel });

    // Build context payload
    const patientTimeline = documents.map((doc: any) => ({
      docId: doc.id,
      fileName: doc.fileName,
      visitDate: doc.visitDate,
      provider: doc.healthcareProvider,
      doctor: doc.doctorName,
      extractedData: doc.extractedData
    }));

    const prompt = `
You are MediGuard AI, an expert medical reasoning assistant.
The user is asking a question about their medical history.
Language to answer in: ${language || 'en'} (en=English, si=Sinhala, ta=Tamil)

Here is the complete chronological patient timeline extracted from multiple documents:
${JSON.stringify(patientTimeline, null, 2)}

Question: "${question}"

Instructions:
1. Answer the question accurately using ONLY the provided timeline data.
2. If the data is missing, say so. Do not hallucinate.
3. For every claim you make, you MUST provide a citation array referencing the "docId" or "fileName" where you found the information.
4. If asked about changes over time, compare the earliest and latest visits.
5. Provide a confidenceScore between 0 and 100 based on how explicitly the answer is stated in the text.

Output a valid JSON object matching exactly this structure:
{
  "answer": "Your detailed answer to the question in the requested language",
  "confidenceScore": number,
  "citations": [
    {
      "docId": "doc id from the timeline",
      "docName": "fileName from the timeline",
      "date": "visitDate from the timeline",
      "quote": "A short exact quote or summary of the extracted data that supports your answer"
    }
  ],
  "disclaimer": "IMPORTANT: This response is generated by MediGuard AI for educational purposes only. It does NOT constitute medical diagnosis or advice."
}

Do NOT output markdown \`\`\`json blocks. Return ONLY raw JSON.
`;

    const result = await model.generateContent(prompt);
    const responseText = result.response.text();
    
    let jsonString = responseText.trim();
    if (jsonString.startsWith('\`\`\`json')) {
      jsonString = jsonString.slice(7, -3).trim();
    } else if (jsonString.startsWith('\`\`\`')) {
      jsonString = jsonString.slice(3, -3).trim();
    }

    const analysis = JSON.parse(jsonString);

    return NextResponse.json({
      success: true,
      answer: analysis.answer,
      confidenceScore: analysis.confidenceScore,
      citations: analysis.citations || [],
      disclaimer: analysis.disclaimer
    });

  } catch (error: any) {
    console.error("API error in chat", error);
    return NextResponse.json({ error: error.message || "Failed to answer question" }, { status: 500 });
  }
}
